export const CardData = [
   {
      id: 1,
      background: "/bg-user-1.png",
      avatar: "/avatar-user-1.jpg",
      username: "@zndrson",
      interact: 256,
      title: "Cosmic Perspective",
      amount: 12000,
   },
   {
      id: 2,
      background: "/bg-user-1.png",
      avatar: "/avatar-user-1.jpg",
      username: "@hudanzs",
      interact: 256,
      title: "Cosmic Perspective",
      amount: 12000,
   },
   {
      id: 3,
      background: "/bg-user-1.png",
      avatar: "/avatar-user-1.jpg",
      username: "@zndrson",
      interact: 256,
      title: "Cosmic Perspective",
      amount: 12000,
   },
   {
      id: 4,
      background: "/bg-user-1.png",
      avatar: "/avatar-user-1.jpg",
      username: "@zndrson",
      interact: 256,
      title: "Cosmic Perspective",
      amount: 12000,
   },
   {
      id: 5,
      background: "/bg-user-1.png",
      avatar: "/avatar-user-1.jpg",
      username: "@zndrson",
      interact: 256,
      title: "Cosmic Perspective",
      amount: 12000,
   },
   {
      id: 6,
      background: "/bg-user-1.png",
      avatar: "/avatar-user-1.jpg",
      username: "@zndrson",
      interact: 256,
      title: "Cosmic Perspective",
      amount: 12000,
   },
]